name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python #python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio #imageio=2.1.2
    - pyqt #pyqt=4.11.4
    - pip:
        - moviepy
        - tensorflow #tensorflow==0.12.1
        - keras #keras==1.2.1
